import type { ModuleDefinition } from './types';

export const MODULE_REGISTRY: ModuleDefinition[] = [
  {
    id: 'ai',
    name: 'LifeOS Asistan',
    nameEn: 'LifeOS Assistant',
    icon: '🤖',
    color: '#6366f1',
    gradient: 'from-indigo-500 to-purple-600',
    category: 'productivity',
    status: 'ACTIVE',
    description: 'Kişisel AI agent ve görev yönetim merkezi',
    descriptionEn: 'Personal AI agent and task management center',
    version: '1.0.0',
    sortOrder: 1,
  },
  {
    id: 'chat',
    name: 'LifeOS Connect',
    nameEn: 'LifeOS Connect',
    icon: '💬',
    color: '#22c55e',
    gradient: 'from-green-400 to-emerald-600',
    category: 'communication',
    status: 'ACTIVE',
    description: 'Sakin, bağlam odaklı mesajlaşma ve LiveKit arama merkezi',
    descriptionEn: 'Calm, context-aware messaging and LiveKit calling hub',
    version: '1.0.0',
    sortOrder: 2,
  },
  {
    id: 'family',
    name: 'Aile',
    nameEn: 'Family',
    icon: '👨‍👩‍👧',
    color: '#f59e0b',
    gradient: 'from-amber-400 to-orange-500',
    category: 'communication',
    status: 'ACTIVE',
    description: 'Aile bağlarını güçlendir',
    descriptionEn: 'Strengthen family bonds',
    version: '1.0.0',
    sortOrder: 3,
  },
  {
    id: 'finance',
    name: 'Finans',
    nameEn: 'Finance',
    icon: '💰',
    color: '#10b981',
    gradient: 'from-emerald-400 to-teal-600',
    category: 'finance',
    status: 'ACTIVE',
    description: 'Finansal hayatını yönet',
    descriptionEn: 'Manage your financial life',
    version: '1.0.0',
    sortOrder: 4,
  },
  {
    id: 'medai',
    name: 'MedAI',
    nameEn: 'MedAI',
    icon: '🩺',
    color: '#ef4444',
    gradient: 'from-red-400 to-rose-600',
    category: 'health',
    status: 'COMING_SOON',
    description: 'AI destekli sağlık asistanın',
    descriptionEn: 'Your AI-powered health assistant',
    version: '1.0.0',
    sortOrder: 5,
  },
  {
    id: 'camera',
    name: 'Kamera',
    nameEn: 'Camera',
    icon: '📷',
    color: '#8b5cf6',
    gradient: 'from-violet-400 to-purple-600',
    category: 'utility',
    status: 'COMING_SOON',
    description: 'Fotoğraf ve videolarını yönet',
    descriptionEn: 'Manage your photos and videos',
    version: '1.0.0',
    sortOrder: 6,
  },
  {
    id: 'smart-home',
    name: 'Akıllı Ev',
    nameEn: 'Smart Home',
    icon: '🏠',
    color: '#0ea5e9',
    gradient: 'from-sky-500 to-indigo-600',
    category: 'home',
    status: 'ACTIVE',
    description: 'İnverter, Solar, Isı Pompası, Kamera, kW Güç ve Ev Aletleri Merkezi',
    descriptionEn: 'Inverter, Solar, Heat Pump, Cameras, kW Power & Appliance Hub',
    version: '1.0.0',
    sortOrder: 7,
  },
  {
    id: 'arcade',
    name: 'Arcade',
    nameEn: 'Arcade',
    icon: '🎮',
    color: '#f43f5e',
    gradient: 'from-rose-400 to-pink-600',
    category: 'entertainment',
    status: 'ACTIVE',
    description: 'LifeOS oyun merkezi',
    descriptionEn: 'LifeOS gaming center',
    version: '1.0.0',
    sortOrder: 9,
  },
  {
    id: 'courses',
    name: 'Dersler',
    nameEn: 'Courses',
    icon: '🎓',
    color: '#3b82f6',
    gradient: 'from-blue-500 to-indigo-600',
    category: 'productivity',
    status: 'ACTIVE',
    description: 'Kurslar, canlı dersler ve akademi merkezi',
    descriptionEn: 'Courses, live sessions and academy hub',
    version: '1.0.0',
    sortOrder: 10,
  },
  {
    id: 'kids',
    name: 'Kids',
    nameEn: 'Kids',
    icon: '🧒',
    color: '#84cc16',
    gradient: 'from-lime-400 to-green-500',
    category: 'entertainment',
    status: 'ACTIVE',
    description: 'Çocuklar için güvenli mini oyunlar, çizgi filmler, masallar ve eğitici dersler',
    descriptionEn: 'Safe mini games, cartoons, stories and study space for kids',
    version: '1.0.0',
    sortOrder: 10,
  },
  {
    id: 'explore',
    name: 'Keşfet',
    nameEn: 'Explore',
    icon: '🧭',
    color: '#3b82f6',
    gradient: 'from-blue-400 to-indigo-500',
    category: 'communication',
    status: 'ACTIVE',
    description: 'Topluluklar ve sana özel akış',
    descriptionEn: 'Communities and personalized feed',
    version: '1.0.0',
    sortOrder: 11,
  },
  {
    id: 'store',
    name: 'Mağaza',
    nameEn: 'Store',
    icon: '🛒',
    color: '#f97316',
    gradient: 'from-orange-400 to-red-500',
    category: 'utility',
    status: 'COMING_SOON',
    description: 'LifeOS uygulama mağazası',
    descriptionEn: 'LifeOS app store',
    version: '1.0.0',
    sortOrder: 12,
  },
  {
    id: 'cloud',
    name: 'Bulut',
    nameEn: 'Cloud',
    icon: '☁️',
    color: '#64748b',
    gradient: 'from-slate-400 to-gray-600',
    category: 'utility',
    status: 'COMING_SOON',
    description: 'Bulut depolama ve yedekleme',
    descriptionEn: 'Cloud storage and backup',
    version: '1.0.0',
    sortOrder: 13,
  },
  {
    id: 'files',
    name: 'Dosyalar',
    nameEn: 'Files',
    icon: '📁',
    color: '#0ea5e9',
    gradient: 'from-sky-400 to-blue-500',
    category: 'productivity',
    status: 'COMING_SOON',
    description: 'Dosyalarını yönet',
    descriptionEn: 'Manage your files',
    version: '1.0.0',
    sortOrder: 14,
  },
  {
    id: 'services',
    name: 'Hizmetler',
    nameEn: 'Services',
    icon: '🛎️',
    color: '#10b981',
    gradient: 'from-amber-500 to-emerald-600',
    category: 'utility',
    status: 'ACTIVE',
    description: 'Taksi, seyahat, nakliye ve usta',
    descriptionEn: 'Taxi, travel, moving and handyman',
    version: '1.0.0',
    sortOrder: 15,
  },
  {
    id: 'emergency',
    name: 'Acil',
    nameEn: 'Emergency',
    icon: '🆘',
    color: '#dc2626',
    gradient: 'from-red-500 to-red-700',
    category: 'utility',
    status: 'COMING_SOON',
    description: 'Acil durum yönetimi',
    descriptionEn: 'Emergency management',
    version: '1.0.0',
    sortOrder: 16,
  },
  {
    id: 'documents',
    name: 'Belgeler',
    nameEn: 'Documents',
    icon: '📄',
    color: '#475569',
    gradient: 'from-slate-400 to-slate-600',
    category: 'productivity',
    status: 'COMING_SOON',
    description: 'Dijital belgelerini sakla',
    descriptionEn: 'Store your digital documents',
    version: '1.0.0',
    sortOrder: 17,
  },
  {
    id: 'media',
    name: 'Medya',
    nameEn: 'Media',
    icon: '🎬',
    color: '#7c3aed',
    gradient: 'from-violet-500 to-purple-700',
    category: 'entertainment',
    status: 'COMING_SOON',
    description: 'Müzik, film ve podcast',
    descriptionEn: 'Music, movies and podcasts',
    version: '1.0.0',
    sortOrder: 18,
  },
  {
    id: 'translate',
    name: 'Çeviri',
    nameEn: 'Translate',
    icon: '🌍',
    color: '#0d9488',
    gradient: 'from-teal-400 to-cyan-600',
    category: 'productivity',
    status: 'COMING_SOON',
    description: 'Anlık çeviri asistanı',
    descriptionEn: 'Real-time translation assistant',
    version: '1.0.0',
    sortOrder: 19,
  },
  {
    id: 'rewards',
    name: 'Ödüller',
    nameEn: 'Rewards',
    icon: '🏆',
    color: '#ca8a04',
    gradient: 'from-yellow-500 to-amber-600',
    category: 'utility',
    status: 'COMING_SOON',
    description: 'LifeOS puan ve ödül sistemi',
    descriptionEn: 'LifeOS points and rewards',
    version: '1.0.0',
    sortOrder: 20,
  },
  {
    id: 'automation',
    name: 'Otomasyon',
    nameEn: 'Automation',
    icon: '⚙️',
    color: '#6b7280',
    gradient: 'from-gray-400 to-gray-600',
    category: 'productivity',
    status: 'COMING_SOON',
    description: 'Hayatını otomatikleştir',
    descriptionEn: 'Automate your life',
    version: '1.0.0',
    sortOrder: 21,
  },
  {
    id: 'app-builder',
    name: 'Uygulama Oluşturucu',
    nameEn: 'App Builder',
    icon: '🧩',
    color: '#ec4899',
    gradient: 'from-pink-400 to-rose-600',
    category: 'productivity',
    status: 'COMING_SOON',
    description: 'Kendi uygulamalarını oluştur',
    descriptionEn: 'Build your own apps',
    version: '1.0.0',
    sortOrder: 22,
  },
  {
    id: 'taxi',
    name: 'Taksi',
    nameEn: 'Taxi',
    icon: '🚕',
    color: '#f59e0b',
    gradient: 'from-amber-400 to-orange-500',
    category: 'utility',
    status: 'ACTIVE',
    description: 'Şehir içi ve şehirlerarası taksi çağırma',
    descriptionEn: 'City and intercity taxi hailing',
    version: '1.0.0',
    sortOrder: 23,
  },
  {
    id: 'travel',
    name: 'Seyahat',
    nameEn: 'Travel',
    icon: '🚌',
    color: '#3b82f6',
    gradient: 'from-blue-400 to-indigo-500',
    category: 'utility',
    status: 'ACTIVE',
    description: 'Otobüs ve seyahat planlama',
    descriptionEn: 'Bus and travel planning',
    version: '1.0.0',
    sortOrder: 24,
  },
  {
    id: 'moving',
    name: 'Nakliye',
    nameEn: 'Moving',
    icon: '🚚',
    color: '#10b981',
    gradient: 'from-emerald-400 to-teal-500',
    category: 'utility',
    status: 'ACTIVE',
    description: 'Evden eve ve parça taşımacılık',
    descriptionEn: 'Moving and logistics',
    version: '1.0.0',
    sortOrder: 25,
  },
  {
    id: 'craftsman',
    name: 'Usta',
    nameEn: 'Craftsman',
    icon: '🛠️',
    color: '#8b5cf6',
    gradient: 'from-purple-400 to-violet-500',
    category: 'utility',
    status: 'ACTIVE',
    description: 'Elektrik, tesisat, boya ve montaj',
    descriptionEn: 'Electric, plumbing, painting and repair',
    version: '1.0.0',
    sortOrder: 26,
  },
];

export function getModuleById(id: string): ModuleDefinition | undefined {
  return MODULE_REGISTRY.find((m) => m.id === id);
}

export function getActiveModules(): ModuleDefinition[] {
  return MODULE_REGISTRY.filter((m) => m.status === 'ACTIVE');
}

export function getModulesByCategory(category: string): ModuleDefinition[] {
  return MODULE_REGISTRY.filter((m) => m.category === category);
}

export function searchModules(query: string, locale: string = 'tr'): ModuleDefinition[] {
  const q = query.toLowerCase();
  return MODULE_REGISTRY.filter((m) => {
    const name = locale === 'tr' ? m.name.toLowerCase() : m.nameEn.toLowerCase();
    const desc = locale === 'tr' ? m.description.toLowerCase() : m.descriptionEn.toLowerCase();
    return name.includes(q) || desc.includes(q) || m.id.includes(q);
  });
}

export const DEFAULT_HOMESCREEN_MODULES = [
  'courses', 'services', 'family', 'finance', 'arcade',
  'kids', 'smart-home', 'ai', 'chat', 'medai',
  'files', 'store', 'rewards',
];

export const DEFAULT_DOCK_MODULES = [
  'services', 'chat', 'ai', 'family',
];

